In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive

'Acies Global Intro Vid - CR Akash Preetham.mp4'
'Ather Energy-Offer Letter.pdf'
 BAIot_CSV.zip
 Classroom
'Colab Notebooks'
 detection+of+iot+botnet+attacks+n+baiot.zip
 EVSE
 EVSE.zip
'Internship Report: One-Month Internship at Zoho IoT Division.gdoc'
'Intrusion Detection System Analysis'
'RA2211053010022-C R Akash Preetham-SRMIST.pdf'
'Saved from Chrome'
'Saved from the Google app'
'Videos '

In [ ]:
!ls -lh /content

total 8.0K
drwx------ 5 root root 4.0K Feb 11 16:41 drive
drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data

In [ ]:
!ls "/content/drive/MyDrive/EVSE.zip"

/content/drive/MyDrive/EVSE.zip

In [ ]:
!unzip "/content/drive/MyDrive/EVSE.zip" -d /content/drive/MyDrive/

Archive:  /content/drive/MyDrive/EVSE.zip
replace /content/drive/MyDrive/EVSE/Host Events/EVSE-B-HPC-Kernel-Events-Combined.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

In [ ]:
import pandas as pd

df_net = pd.read_csv(
    "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-A/csv/EVSE-A-charging-Aggressive-scan.csv"
)

print(df_net.shape)
print(df_net.columns)
df_net.head()

(9999, 86)
Index(['id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui', 'src_port',
       'dst_ip', 'dst_mac', 'dst_oui', 'dst_port', 'protocol', 'ip_version',
       'vlan_id', 'tunnel_id', 'bidirectional_first_seen_ms',
       'bidirectional_last_seen_ms', 'bidirectional_duration_ms',
       'bidirectional_packets', 'bidirectional_bytes', 'src2dst_first_seen_ms',
       'src2dst_last_seen_ms', 'src2dst_duration_ms', 'src2dst_packets',
       'src2dst_bytes', 'dst2src_first_seen_ms', 'dst2src_last_seen_ms',
       'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes',
       'bidirectional_min_ps', 'bidirectional_mean_ps',
       'bidirectional_stddev_ps', 'bidirectional_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'src2dst_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'dst2src_max_ps', 'bidirectional_min_piat_ms',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'src2dst_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'dst2src_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'bidirectional_syn_packets',
       'bidirectional_cwr_packets', 'bidirectional_ece_packets',
       'bidirectional_urg_packets', 'bidirectional_ack_packets',
       'bidirectional_psh_packets', 'bidirectional_rst_packets',
       'bidirectional_fin_packets', 'src2dst_syn_packets',
       'src2dst_cwr_packets', 'src2dst_ece_packets', 'src2dst_urg_packets',
       'src2dst_ack_packets', 'src2dst_psh_packets', 'src2dst_rst_packets',
       'src2dst_fin_packets', 'dst2src_syn_packets', 'dst2src_cwr_packets',
       'dst2src_ece_packets', 'dst2src_urg_packets', 'dst2src_ack_packets',
       'dst2src_psh_packets', 'dst2src_rst_packets', 'dst2src_fin_packets',
       'application_name', 'application_category_name',
       'application_is_guessed', 'application_confidence',
       'requested_server_name', 'client_fingerprint', 'server_fingerprint',
       'user_agent', 'content_type'],
      dtype='object')

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,256,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,993,...,0,IMAPS,Email,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,139,...,0,NetBIOS,System,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,143,...,0,IMAP,Email,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,135,...,0,RPC,RPC,1,1,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_host = pd.read_csv(
    "/content/drive/MyDrive/EVSE/Host Events/EVSE-B-HPC-Kernel-Events-Combined.csv"
)

print(df_host.shape)
print(df_host.columns)
df_host.head()

(8474, 915)
Index(['time', 'alarmtimer_alarmtimer_cancel', 'alarmtimer_alarmtimer_fired',
       'alarmtimer_alarmtimer_start', 'alarmtimer_alarmtimer_suspend',
       'alignment-faults', 'ase_spec', 'block_block_bio_backmerge',
       'block_block_bio_bounce', 'block_block_bio_complete',
       ...
       'writeback_writeback_written', 'State', 'Attack', 'Scenario', 'Label',
       'interface', 'Unnamed: 911', 'Unnamed: 912', 'Unnamed: 913',
       'Unnamed: 914'],
      dtype='object', length=915)

/tmp/ipython-input-2063648650.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,911,912,913,914) have mixed types. Specify dtype option on import or set low_memory=False.
  df_host = pd.read_csv(

,time,alarmtimer_alarmtimer_cancel,alarmtimer_alarmtimer_fired,alarmtimer_alarmtimer_start,alarmtimer_alarmtimer_suspend,alignment-faults,ase_spec,block_block_bio_backmerge,block_block_bio_bounce,block_block_bio_complete,...,writeback_writeback_written,State,Attack,Scenario,Label,interface,Unnamed: 911,Unnamed: 912,Unnamed: 913,Unnamed: 914
0,5.001477,0,0,0,0,0,693371795,0,0,0,...,0,Charging,cryptojacking,Cryptojacking,attack,any,NaN,NaN,NaN,NaN
1,5.001487,0,0,0,0,0,699964025,0,0,0,...,0,Charging,cryptojacking,Cryptojacking,attack,any,NaN,NaN,NaN,NaN
2,5.001641,0,0,0,0,0,549770341,0,0,0,...,0,Charging,cryptojacking,Cryptojacking,attack,any,NaN,NaN,NaN,NaN
3,5.003762,0,0,0,0,0,571970875,0,0,0,...,0,Charging,cryptojacking,Cryptojacking,attack,any,NaN,NaN,NaN,NaN
4,10.06574,0,0,0,0,0,553199786,0,0,0,...,0,Charging,cryptojacking,Cryptojacking,attack,any,NaN,NaN,NaN,NaN

In [ ]:
df_power = pd.read_csv(
    "/content/drive/MyDrive/EVSE/Power Consumption/EVSE-B-PowerCombined.csv"
)

print(df_power.shape)
print(df_power.columns)
df_power.head()

(115298, 10)
Index(['time', 'shunt_voltage', 'bus_voltage_V', 'current_mA', 'power_mW',
       'State', 'Attack', 'Attack-Group', 'Label', 'interface'],
      dtype='object')

,time,shunt_voltage,bus_voltage_V,current_mA,power_mW,State,Attack,Attack-Group,Label,interface
0,12/25/2023 22:35,978,5.165,1027,5300,idle,syn-flood,DoS,attack,ocpp
1,12/25/2023 22:35,872,5.161,1009,4980,idle,syn-flood,DoS,attack,ocpp
2,12/25/2023 22:35,1017,5.165,1029,5300,idle,syn-flood,DoS,attack,ocpp
3,12/25/2023 22:35,930,5.161,1005,5180,idle,syn-flood,DoS,attack,ocpp
4,12/25/2023 22:35,958,5.165,1034,5180,idle,syn-flood,DoS,attack,ocpp

In [ ]:
# =========================
# EVSE-A CLEANING PIPELINE
# =========================

import os
import pandas as pd
import numpy as np

# ---- PATHS ----
EVSE_A_PATH = "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-A/csv" # Corrected path
OUTPUT_PATH = "/content/drive/MyDrive/EVSE/cleaned"
os.makedirs(OUTPUT_PATH, exist_ok=True)

# ---- Helper function to extract label from filename ----
def extract_label_from_filename(filename):
    name_without_ext = os.path.splitext(filename)[0] # remove .csv
    parts = name_without_ext.split('-')

    # Assuming the label is the part(s) after 'charging' or 'idle'
    if 'charging' in parts:
        start_index = parts.index('charging') + 1
    elif 'idle' in parts:
        start_index = parts.index('idle') + 1
    else:
        return 'UNKNOWN' # Fallback for unexpected filenames

    label_parts = parts[start_index:]
    return '-'.join(label_parts).replace(' ', '_').upper()

# ---- LOAD & CONCATENATE ALL EVSE-A CSVs ----
dfs = []
for f in sorted(os.listdir(EVSE_A_PATH)):
    if f.endswith(".csv"):
        file_path = os.path.join(EVSE_A_PATH, f)
        temp_df = pd.read_csv(file_path)
        temp_df['Attack_Type'] = extract_label_from_filename(f) # Add new label column
        dfs.append(temp_df)

df_a = pd.concat(dfs, ignore_index=True)
print("EVSE-A raw shape:", df_a.shape)

# ---- IDENTIFY LABEL COLUMN (AUTO) ----
# Now, 'Attack_Type' should be found
label_candidates = [c for c in df_a.columns if any(k in c.lower() for k in ["label", "attack", "class", "attack_type"])]
assert len(label_candidates) == 1, f"Expected 1 label column, found: {label_candidates}"
LABEL_COL = label_candidates[0]
print("Label column:", LABEL_COL)

# ---- DROP NON-FEATURE (IDENTIFIER) COLUMNS ----
non_feature_cols = [
    'id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui',
    'dst_ip', 'dst_mac', 'dst_oui',
    'application_name', 'application_category_name',
    'requested_server_name', 'client_fingerprint', 'server_fingerprint',
    'user_agent', 'content_type'
]
df_a.drop(columns=non_feature_cols, inplace=True, errors="ignore")
print("Dropped non-feature columns:", non_feature_cols)

# ---- HANDLE INF / NAN ----
df_a.replace([np.inf, -np.inf], np.nan, inplace=True)

numeric_cols = df_a.select_dtypes(include="number").columns
# Calculate medians; if a column is all NaN, its median will be NaN
medians = df_a[numeric_cols].median()
# Fill NaNs using medians; if a median is NaN, use 0 as fallback
df_a[numeric_cols] = df_a[numeric_cols].fillna(medians.fillna(0))

# ---- ENSURE LABEL IS CLEAN ----
df_a[LABEL_COL] = df_a[LABEL_COL].astype(str).str.strip().str.upper()

# (Optional) Binary labels example:
# df_a[LABEL_COL] = df_a[LABEL_COL].apply(lambda x: 0 if x == "BENIGN" else 1)

# ---- FINAL SANITY CHECKS ----
assert not df_a[numeric_cols].isna().any().any(), "NaNs remain in numeric features after imputation."
assert not np.isinf(df_a[numeric_cols]).any().any(), "Infs remain in numeric features"

print("EVSE-A cleaned shape:", df_a.shape)
print(df_a[LABEL_COL].value_counts().head())

# ---- SAVE CLEAN DATASET ----
out_a = os.path.join(OUTPUT_PATH, "EVSE-A_clean.csv")
df_a.to_csv(out_a, index=False)
print("Saved:", out_a)

/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,82,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-3771490644.py:35: DtypeWarning: Columns (81,83) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)

EVSE-A raw shape: (547854, 87)
Label column: Attack_Type
Dropped non-feature columns: ['id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui', 'dst_ip', 'dst_mac', 'dst_oui', 'application_name', 'application_category_name', 'requested_server_name', 'client_fingerprint', 'server_fingerprint', 'user_agent', 'content_type']
EVSE-A cleaned shape: (547854, 72)
Attack_Type
SYN-FLOOD         131107
SYNONYMOUS-IP     131093
TCP-FLOOD         131087
PUSH-ACK-FLOOD     65536
UDP-FLOOD          15956
Name: count, dtype: int64
Saved: /content/drive/MyDrive/EVSE/cleaned/EVSE-A_clean.csv

In [ ]:
# =========================
# EVSE-B CLEANING PIPELINE
# =========================

import os
import pandas as pd
import numpy as np

# ---- PATHS ----
EVSE_B_PATH = "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-B/csv" # Corrected path
OUTPUT_PATH = "/content/drive/MyDrive/EVSE/cleaned"
os.makedirs(OUTPUT_PATH, exist_ok=True)

# ---- Helper function to extract label from filename ----
def extract_label_from_filename(filename):
    name_without_ext = os.path.splitext(filename)[0] # remove .csv
    parts = name_without_ext.split('-')

    # Assuming the label is the part(s) after 'charging' or 'idle'
    if 'charging' in parts:
        start_index = parts.index('charging') + 1
    elif 'idle' in parts:
        start_index = parts.index('idle') + 1
    else:
        return 'UNKNOWN' # Fallback for unexpected filenames

    label_parts = parts[start_index:]
    return '-'.join(label_parts).replace(' ', '_').upper()

# ---- LOAD & CONCATENATE ALL EVSE-B CSVs ----
dfs = []
for f in sorted(os.listdir(EVSE_B_PATH)):
    if f.endswith(".csv"):
        file_path = os.path.join(EVSE_B_PATH, f)
        temp_df = pd.read_csv(file_path)
        temp_df['Attack_Type'] = extract_label_from_filename(f) # Add new label column
        dfs.append(temp_df)

df_b = pd.concat(dfs, ignore_index=True)
print("EVSE-B raw shape:", df_b.shape)

# ---- IDENTIFY LABEL COLUMN (AUTO) ----
# Now, 'Attack_Type' should be found
label_candidates = [c for c in df_b.columns if any(k in c.lower() for k in ["label", "attack", "class", "attack_type"])]
assert len(label_candidates) == 1, f"Expected 1 label column, found: {label_candidates}"
LABEL_COL = label_candidates[0]
print("Label column:", LABEL_COL)

# ---- DROP NON-FEATURE (IDENTIFIER) COLUMNS ----
non_feature_cols = [
    'id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui',
    'dst_ip', 'dst_mac', 'dst_oui',
    'application_name', 'application_category_name',
    'requested_server_name', 'client_fingerprint', 'server_fingerprint',
    'user_agent', 'content_type'
]
df_b.drop(columns=non_feature_cols, inplace=True, errors="ignore")
print("Dropped non-feature columns:", non_feature_cols)

# ---- HANDLE INF / NAN ----
df_b.replace([np.inf, -np.inf], np.nan, inplace=True)

numeric_cols = df_b.select_dtypes(include="number").columns
# Calculate medians; if a column is all NaN, its median will be NaN
medians = df_b[numeric_cols].median()
# Fill NaNs using medians; if a median is NaN, use 0 as fallback
df_b[numeric_cols] = df_b[numeric_cols].fillna(medians.fillna(0))

# ---- ENSURE LABEL IS CLEAN ----
df_b[LABEL_COL] = df_b[LABEL_COL].astype(str).str.strip().str.upper()

# (Optional) Binary labels example:
# df_b[LABEL_COL] = df_b[LABEL_COL].apply(lambda x: 0 if x == "BENIGN" else 1)

# ---- FINAL SANITY CHECKS ----
assert not df_b[numeric_cols].isna().any().any(), "NaNs remain in numeric features after imputation."
assert not np.isinf(df_b[numeric_cols]).any().any(), "Infs remain in numeric features"

print("EVSE-B cleaned shape:", df_b.shape)
print(df_b[LABEL_COL].value_counts().head())

# ---- SAVE CLEAN DATASET ----
out_b = os.path.join(OUTPUT_PATH, "EVSE-B_clean.csv")
df_b.to_csv(out_b, index=False)
print("Saved:", out_b)

/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)
/tmp/ipython-input-1926621223.py:35: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file_path)

EVSE-B raw shape: (2196846, 87)
Label column: Attack_Type
Dropped non-feature columns: ['id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui', 'dst_ip', 'dst_mac', 'dst_oui', 'application_name', 'application_category_name', 'requested_server_name', 'client_fingerprint', 'server_fingerprint', 'user_agent', 'content_type']
EVSE-B cleaned shape: (2196846, 72)
Attack_Type
UNKNOWN                   564781
PORT-SCAN                 255554
SYN-STEALTH               214065
SERVICE-DETECTION-SCAN    165171
VULNERABILITY-SCAN        161728
Name: count, dtype: int64
Saved: /content/drive/MyDrive/EVSE/cleaned/EVSE-B_clean.csv

In [ ]:
import pandas as pd
import numpy as np

A_PATH = "/content/drive/MyDrive/EVSE/cleaned/EVSE-A_clean.csv"
B_PATH = "/content/drive/MyDrive/EVSE/cleaned/EVSE-B_clean.csv"

df_a = pd.read_csv(A_PATH)
df_b = pd.read_csv(B_PATH)

print("EVSE-A shape:", df_a.shape)
print("EVSE-B shape:", df_b.shape)

# Identify label column automatically
label_candidates = [c for c in df_a.columns if any(k in c.lower() for k in ["label","attack","class"])]
assert len(label_candidates)==1, label_candidates
LABEL = label_candidates[0]
print("Label column:", LABEL)

df_a[LABEL].value_counts().head(), df_b[LABEL].value_counts().head()

EVSE-A shape: (547854, 72)
EVSE-B shape: (2196846, 72)
Label column: Attack_Type

(Attack_Type
 SYN-FLOOD         131107
 SYNONYMOUS-IP     131093
 TCP-FLOOD         131087
 PUSH-ACK-FLOOD     65536
 UDP-FLOOD          15956
 Name: count, dtype: int64,
 Attack_Type
 UNKNOWN                   564781
 PORT-SCAN                 255554
 SYN-STEALTH               214065
 SERVICE-DETECTION-SCAN    165171
 VULNERABILITY-SCAN        161728
 Name: count, dtype: int64)

In [ ]:
# Binary labels: BENIGN=0, ATTACK=1
def binarize(y):
    return (y.astype(str).str.upper() != "BENIGN").astype(int)

X_train = df_a.drop(columns=[LABEL])
y_train = binarize(df_a[LABEL])

X_test  = df_b.drop(columns=[LABEL])
y_test  = binarize(df_b[LABEL])

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Train attack rate:", y_train.mean(), "Test attack rate:", y_test.mean())

Train: (547854, 71) Test: (2196846, 71)
Train attack rate: 0.9998758793401161 Test attack rate: 1.0

In [ ]:
print("df_a Attack_Type value counts:")
print(df_a['Attack_Type'].value_counts())
print("\n" + "df_b Attack_Type value counts:")
print(df_b['Attack_Type'].value_counts())

df_a Attack_Type value counts:
Attack_Type
SYN-FLOOD             131107
SYNONYMOUS-IP         131093
TCP-FLOOD             131087
PUSH-ACK-FLOOD         65536
UDP-FLOOD              15956
PORTSCAN               13092
VULNERABILITY-SCAN     12581
AGGRESSIVE-SCAN        12332
OS-FINGERPRINTING       8381
SYN-STEALTH             8032
SYN-STEALTH-SCAN        7215
SERVICE-DETECTION       7141
SLOWLORIS-SCAN          4201
BENIGN                    68
ICMP-FRAGMENTATION        16
UNKNOWN                   14
ICMP-FLOOD                 2
Name: count, dtype: int64

df_b Attack_Type value counts:
Attack_Type
UNKNOWN                   564781
PORT-SCAN                 255554
SYN-STEALTH               214065
SERVICE-DETECTION-SCAN    165171
VULNERABILITY-SCAN        161728
PUSH-ACK-FLOOD            131118
TCP-FLOOD                 131107
SYNONYMOUS-IP-FLOOD       131092
SYN-FLOOD                 131089
OS-FINGERPRINTING         113633
AGGRESSIVE-SCAN            73829
SYN-STEALTH-SCAN           73633
SERVICE-DETECTION          33455
UDP-FLOOD                  16519
ICMP-FLOOD                    60
ICMP-FRAGMENTATION            12
Name: count, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

A_PATH = "/content/drive/MyDrive/EVSE/cleaned/EVSE-A_clean.csv"
B_PATH = "/content/drive/MyDrive/EVSE/cleaned/EVSE-B_clean.csv"

df_a = pd.read_csv(A_PATH)
df_b = pd.read_csv(B_PATH)

# Detect label column automatically
label_candidates = [c for c in df_a.columns if any(k in c.lower() for k in ["label","attack","class"])]
assert len(label_candidates) == 1, label_candidates
LABEL = label_candidates[0]

print("Label column:", LABEL)
print("EVSE-A shape:", df_a.shape)
print("EVSE-B shape:", df_b.shape)

Label column: Attack_Type
EVSE-A shape: (547854, 72)
EVSE-B shape: (2196846, 72)

In [ ]:
# Binary encoding: BENIGN = 0, ATTACK = 1
def binarize(y):
    return (y.astype(str).str.upper() != "BENIGN").astype(int)

X_train = df_a.drop(columns=[LABEL])
y_train = binarize(df_a[LABEL])

X_test  = df_b.drop(columns=[LABEL])
y_test  = binarize(df_b[LABEL])

print("Train shape:", X_train.shape, "Test shape:", X_test.shape)
print("Train attack ratio:", y_train.mean())
print("Test attack ratio:", y_test.mean())

Train shape: (547854, 71) Test shape: (2196846, 71)
Train attack ratio: 0.9998758793401161
Test attack ratio: 1.0