In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!ls /content/drive/MyDrive
!ls -lh /content
!ls "/content/drive/MyDrive/EVSE.zip"
!unzip "/content/drive/MyDrive/EVSE.zip" -d /content/drive/MyDrive/

'Acies Global Intro Vid - CR Akash Preetham.mp4'
'Ather Energy-Offer Letter.pdf'
'Ather Report.gslides'
 BAIot_CSV.zip
 Classroom
'Colab Notebooks'
'C R AKASH PREETHAM_Doc (3).pdf'
 detection+of+iot+botnet+attacks+n+baiot.zip
 EVSE
 EVSE.zip
'Google AI Studio'
'INTERNSHIP PROJECT REPORT.gdoc'
'Internship Report: One-Month Internship at Zoho IoT Division.gdoc'
'Intrusion Detection System Analysis'
'RA2211053010022-C R Akash Preetham-SRMIST.pdf'
'Saved from Chrome'
'Saved from the Google app'
'Videos '
total 8.0K
drwx------ 5 root root 4.0K Mar  1 08:49 drive
drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data
/content/drive/MyDrive/EVSE.zip
Archive:  /content/drive/MyDrive/EVSE.zip
replace /content/drive/MyDrive/EVSE/Host Events/EVSE-B-HPC-Kernel-Events-Combined.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

In [4]:
!ls -lh /content

total 8.0K
drwx------ 5 root root 4.0K Mar  1 08:49 drive
drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data

In [5]:
!ls "/content/drive/MyDrive/EVSE.zip"

/content/drive/MyDrive/EVSE.zip

In [6]:
!unzip "/content/drive/MyDrive/EVSE.zip" -d /content/drive/MyDrive/

Archive:  /content/drive/MyDrive/EVSE.zip
replace /content/drive/MyDrive/EVSE/Host Events/EVSE-B-HPC-Kernel-Events-Combined.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

In [7]:
!ls "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-A/csv/"

EVSE-A-charging-Aggressive-scan.csv	EVSE-A-charging-vulnerability-scan.csv
EVSE-A-Charging-Benign.csv		EVSE-A-idle-aggressive-scan.csv
EVSE-A-charging-icmp-flood.csv		EVSE-A-idle-benign.csv
EVSE-A-charging-icmp-fragmentation.csv	EVSE-A-idle-icmp-fragmentation.csv
EVSE-A-charging-os-fingerprinting.csv	EVSE-A-idle-os-fingerprinting.csv
EVSE-A-charging-portscan.csv		EVSE-A-idle-portscan.csv
EVSE-A-charging-push-ack-flood.csv	EVSE-A-idle-service-detection.csv
EVSE-A-charging-service-detection.csv	EVSE-A-idle-slowloris-scan.csv
EVSE-A-charging-slowLoris-scan.csv	EVSE-A-idle-syn-flood.csv
EVSE-A-charging-syn-flood.csv		EVSE-A-idle-synonymous-ip.csv
EVSE-A-charging-synonymous-ip.csv	EVSE-A-idle-syn-stealth-scan.csv
EVSE-A-charging-syn-stealth.csv		EVSE-A-idle-tcp-flood.csv
EVSE-A-charging-tcp-flood.csv		EVSE-A-idle-udp-flood.csv
EVSE-A-charging-udp-flood.csv		EVSE-A-idle-vulnerability-scan.csv

In [8]:
import pandas as pd

df_net = pd.read_csv(
    "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-A/csv/EVSE-A-charging-Aggressive-scan.csv"
)

print(df_net.shape)
print(df_net.columns)
df_net.head()

(9999, 86)
Index(['id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui', 'src_port',
       'dst_ip', 'dst_mac', 'dst_oui', 'dst_port', 'protocol', 'ip_version',
       'vlan_id', 'tunnel_id', 'bidirectional_first_seen_ms',
       'bidirectional_last_seen_ms', 'bidirectional_duration_ms',
       'bidirectional_packets', 'bidirectional_bytes', 'src2dst_first_seen_ms',
       'src2dst_last_seen_ms', 'src2dst_duration_ms', 'src2dst_packets',
       'src2dst_bytes', 'dst2src_first_seen_ms', 'dst2src_last_seen_ms',
       'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes',
       'bidirectional_min_ps', 'bidirectional_mean_ps',
       'bidirectional_stddev_ps', 'bidirectional_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'src2dst_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'dst2src_max_ps', 'bidirectional_min_piat_ms',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'src2dst_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'dst2src_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'bidirectional_syn_packets',
       'bidirectional_cwr_packets', 'bidirectional_ece_packets',
       'bidirectional_urg_packets', 'bidirectional_ack_packets',
       'bidirectional_psh_packets', 'bidirectional_rst_packets',
       'bidirectional_fin_packets', 'src2dst_syn_packets',
       'src2dst_cwr_packets', 'src2dst_ece_packets', 'src2dst_urg_packets',
       'src2dst_ack_packets', 'src2dst_psh_packets', 'src2dst_rst_packets',
       'src2dst_fin_packets', 'dst2src_syn_packets', 'dst2src_cwr_packets',
       'dst2src_ece_packets', 'dst2src_urg_packets', 'dst2src_ack_packets',
       'dst2src_psh_packets', 'dst2src_rst_packets', 'dst2src_fin_packets',
       'application_name', 'application_category_name',
       'application_is_guessed', 'application_confidence',
       'requested_server_name', 'client_fingerprint', 'server_fingerprint',
       'user_agent', 'content_type'],
      dtype='object')

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,256,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
1,1,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,993,...,0,IMAPS,Email,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,139,...,0,NetBIOS,System,1,1,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,143,...,0,IMAP,Email,1,1,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,42750,192.168.137.226,0c:8b:95:09:c6:08,0c:8b:95,135,...,0,RPC,RPC,1,1,NaN,NaN,NaN,NaN,NaN

In [9]:
!ls "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-B/csv/"

EVSE-B-charging-aggressive-scan.csv
EVSE-B-charging-icmp-flood.csv
EVSE-B-charging-os-fingerprinting.csv
EVSE-B-charging-port-scan.csv
EVSE-B-charging-push-ack-flood.csv
EVSE-B-charging-service-detection-scan.csv
EVSE-B-charging-syn-flood.csv
EVSE-B-charging-synonymous-ip-flood.csv
EVSE-B-charging-syn-stealth.csv
EVSE-B-charging-tcp-flood.csv
EVSE-B-charging-udp-flood.csv
EVSE-B-charging-vulnerability-scan.csv
EVSE-B-idle-aggressive-scan.csv
EVSE-B-idle-icmp-flood.csv
EVSE-B-idle-icmp-fragmentation.csv
EVSE-B-idle-os-fingerprinting.csv
EVSE-B-idle-port-scan.csv
EVSE-B-idle-push-ack-flood.csv
EVSE-B-idle-service-detection.csv
EVSE-B-idle-syn-flood.csv
EVSE-B-idle-synonymous-ip-flood.csv
EVSE-B-idle-syn-stealth-scan.csv
EVSE-B-idle-tcp-flood.csv
EVSE-B-idle-udp-flood.csv
EVSE-B-idle-vulnerability-scan.csv
EVSE-B-MaliciousEV-aggressive-scan.csv
EVSE-B-MaliciousEV-os-fingerprinting.csv
EVSE-B-MaliciousEV-port-scan.csv
EVSE-B-MaliciousEV-service-detection.csv
EVSE-B-MaliciousEV-syn-stealth-scan.csv
EVSE-B-MaliciousEV-vulnerability-scan.csv

In [10]:
import pandas as pd

df_net = pd.read_csv(
    "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-B/csv/EVSE-B-charging-aggressive-scan.csv"
)

print(df_net.shape)
print(df_net.columns)
df_net.head()

(37872, 86)
Index(['id', 'expiration_id', 'src_ip', 'src_mac', 'src_oui', 'src_port',
       'dst_ip', 'dst_mac', 'dst_oui', 'dst_port', 'protocol', 'ip_version',
       'vlan_id', 'tunnel_id', 'bidirectional_first_seen_ms',
       'bidirectional_last_seen_ms', 'bidirectional_duration_ms',
       'bidirectional_packets', 'bidirectional_bytes', 'src2dst_first_seen_ms',
       'src2dst_last_seen_ms', 'src2dst_duration_ms', 'src2dst_packets',
       'src2dst_bytes', 'dst2src_first_seen_ms', 'dst2src_last_seen_ms',
       'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes',
       'bidirectional_min_ps', 'bidirectional_mean_ps',
       'bidirectional_stddev_ps', 'bidirectional_max_ps', 'src2dst_min_ps',
       'src2dst_mean_ps', 'src2dst_stddev_ps', 'src2dst_max_ps',
       'dst2src_min_ps', 'dst2src_mean_ps', 'dst2src_stddev_ps',
       'dst2src_max_ps', 'bidirectional_min_piat_ms',
       'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms',
       'bidirectional_max_piat_ms', 'src2dst_min_piat_ms',
       'src2dst_mean_piat_ms', 'src2dst_stddev_piat_ms', 'src2dst_max_piat_ms',
       'dst2src_min_piat_ms', 'dst2src_mean_piat_ms', 'dst2src_stddev_piat_ms',
       'dst2src_max_piat_ms', 'bidirectional_syn_packets',
       'bidirectional_cwr_packets', 'bidirectional_ece_packets',
       'bidirectional_urg_packets', 'bidirectional_ack_packets',
       'bidirectional_psh_packets', 'bidirectional_rst_packets',
       'bidirectional_fin_packets', 'src2dst_syn_packets',
       'src2dst_cwr_packets', 'src2dst_ece_packets', 'src2dst_urg_packets',
       'src2dst_ack_packets', 'src2dst_psh_packets', 'src2dst_rst_packets',
       'src2dst_fin_packets', 'dst2src_syn_packets', 'dst2src_cwr_packets',
       'dst2src_ece_packets', 'dst2src_urg_packets', 'dst2src_ack_packets',
       'dst2src_psh_packets', 'dst2src_rst_packets', 'dst2src_fin_packets',
       'application_name', 'application_category_name',
       'application_is_guessed', 'application_confidence',
       'requested_server_name', 'client_fingerprint', 'server_fingerprint',
       'user_agent', 'content_type'],
      dtype='object')

/tmp/ipython-input-6436/2425055184.py:3: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  df_net = pd.read_csv(

,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,dst_port,...,dst2src_fin_packets,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type
0,0,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,33682,192.168.137.198,dc:a6:32:c9:e5:5e,dc:a6:32,22,...,1,SSH,RemoteAccess,0,6,NaN,E788C657D1A22971D5026526FFD2E918,41FF3ECD1458B0BF86E1B4891636213E,NaN,NaN
1,1,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,47450,192.168.137.198,dc:a6:32:c9:e5:5e,dc:a6:32,22,...,0,SSH,RemoteAccess,1,1,NaN,NaN,NaN,NaN,NaN
2,2,0,fe80::813f:cb21:c6d4:b7c2,dc:a6:32:c9:e5:5e,dc:a6:32,49152,fe80::6c9b:9e0d:591c:fc8a,dc:a6:32:c9:e6:9f,dc:a6:32,34084,...,0,TLS,Web,0,6,NaN,NaN,NaN,NaN,NaN
3,3,0,192.168.137.198,dc:a6:32:c9:e5:5f,dc:a6:32,33234,192.168.137.87,dc:a6:32:c9:e5:3e,dc:a6:32,8765,...,0,Unknown,Unspecified,0,0,NaN,NaN,NaN,NaN,NaN
4,4,0,192.168.137.85,a8:6b:ad:1f:9b:e5,a8:6b:ad,50534,192.168.137.198,dc:a6:32:c9:e5:5f,dc:a6:32,139,...,0,NetBIOS,System,1,1,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd
import numpy as np
import os
import glob

# Folder path
folder_path = "/content/drive/MyDrive/EVSE/Network Traffic/EVSE-B/csv"

# Get all CSV files
all_files = glob.glob(os.path.join(folder_path, "*.csv"))

print("Total files found:", len(all_files))

# Combine all files
df_list = []

for file in all_files:
    temp_df = pd.read_csv(file)

    # Create label from filename
    filename = os.path.basename(file).lower()

    if "benign" in filename:
        temp_df["Target"] = 0
    else:
        temp_df["Target"] = 1

    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

print("Combined dataset shape:", df.shape)

Total files found: 31

/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81,82,84) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)
/tmp/ipython-input-6436/792277575.py:18: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(file)

Combined dataset shape: (2196846, 87)

In [12]:
# Remove leakage columns safely
leakage_keywords = ['scenario', 'label', 'attack', 'type', 'class']

columns_to_drop = []

for col in df.columns:
    for keyword in leakage_keywords:
        if keyword in col.lower():
            columns_to_drop.append(col)
            break

print("Dropping columns:", columns_to_drop)

df = df.drop(columns=columns_to_drop, errors='ignore')

Dropping columns: ['content_type']

In [13]:
y = df["Target"]
X = df.drop(columns=["Target"])

# Keep only numeric columns
X = X.select_dtypes(include=[np.number])

# Remove NaNs
X = X.replace([np.inf, -np.inf], np.nan)
X = X.dropna()
y = y.loc[X.index]

print("Final feature shape:", X.shape)

Final feature shape: (2196846, 73)

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Remove NaNs
X = X.dropna()
y = y.loc[X.index]

# Keep only numeric columns
X = X.select_dtypes(include=[np.number])

# Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Stratified split (VERY IMPORTANT)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (1757476, 73)
Test size: (439370, 73)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

log_model = LogisticRegression(class_weight='balanced', max_iter=1000)
log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

print("Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print(confusion_matrix(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(1)

In [17]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Results")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Results
Accuracy: 1.0
[[439370]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00    439370

    accuracy                           1.00    439370
   macro avg       1.00      1.00      1.00    439370
weighted avg       1.00      1.00      1.00    439370

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [18]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),
    eval_metric='logloss',
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

print("XGBoost Results")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]

In [ ]:
from sklearn.metrics import roc_auc_score

print("RF AUC:", roc_auc_score(y_test, rf_model.predict_proba(X_test)[:,1]))
print("XGB AUC:", roc_auc_score(y_test, xgb_model.predict_proba(X_test)[:,1]))

In [20]:
leakage_keywords = [
    'scenario', 'label', 'attack', 'type',
    'class', 'state', 'service', 'scan'
]

drop_cols = []

for col in df.columns:
    for key in leakage_keywords:
        if key in col.lower():
            drop_cols.append(col)
            break

df = df.drop(columns=drop_cols, errors='ignore')

print("After dropping leakage:", df.shape)

After dropping leakage: (2196846, 86)

In [21]:
allowed_keywords = [
    'packet', 'byte', 'length', 'duration',
    'iat', 'flag', 'rate', 'window', 'ttl'
]

selected_cols = []

for col in df.columns:
    for key in allowed_keywords:
        if key in col.lower():
            selected_cols.append(col)
            break

selected_cols.append("Target")

df = df[selected_cols]

print("After aggressive filtering:", df.shape)

After aggressive filtering: (2196846, 46)

In [22]:
# Keep only numeric
df = df.select_dtypes(include=[np.number])

# Remove NaNs
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()

y = df["Target"]
X = df.drop(columns=["Target"])

# Correlation with target
corr = X.corrwith(y).abs()

# Select top 15 only
top_features = corr.sort_values(ascending=False).head(15).index

X = X[top_features]

print("Final feature count:", len(top_features))
print("Selected features:", list(top_features))

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Final feature count: 15
Selected features: ['bidirectional_duration_ms', 'bidirectional_packets', 'bidirectional_bytes', 'src2dst_duration_ms', 'src2dst_packets', 'src2dst_bytes', 'dst2src_duration_ms', 'dst2src_packets', 'dst2src_bytes', 'bidirectional_min_piat_ms', 'bidirectional_mean_piat_ms', 'bidirectional_stddev_piat_ms', 'bidirectional_max_piat_ms', 'src2dst_min_piat_ms', 'src2dst_mean_piat_ms']

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(1)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.6,
    stratify=y,
    random_state=42
)

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=80,        # not too high
    max_depth=6,             # restrict depth
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

Confusion Matrix:
 [[1318108]]

Classification Report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00   1318108

    accuracy                           1.00   1318108
   macro avg       1.00      1.00      1.00   1318108
weighted avg       1.00      1.00      1.00   1318108